language: python

python:
  - "2.7"
  - "3.3"
  - "3.4"

install:
  - "if [[ $TRAVIS_PYTHON_VERSION == '2.7' ]]; then pip install -r requirements/base.txt; fi"
  - "if [[ $TRAVIS_PYTHON_VERSION == '3.3' ]]; then pip install -r requirements/py3.txt; fi"
  - "if [[ $TRAVIS_PYTHON_VERSION == '3.4' ]]; then pip install -r requirements/py3.txt; fi"

script:
  - "python setup.py test"
